# Generated by Django 5.0.3 on 2024-12-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity_in_Stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=19)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('last_sale_date', models.DateField(auto_now=True)),
                ('description', models.TextField(default='stock Item')),
                ('sell', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('cummulative_quantity_sold', models.IntegerField(default=0)),
                ('cumulative_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('size', models.PositiveIntegerField(default=0, null=0)),
                ('label', models.TextField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_damaged', models.PositiveIntegerField()),
                ('damage_description', models.TextField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField()),
                ('return_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('label', models.TextField(default='', max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('opening_stock', models.IntegerField()),
                ('closing_stock', models.IntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
