# Generated by Django 5.0.3 on 2025-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-stock_date']},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='closing_stock',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='opening_stock',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='In', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
