# Generated by Django 5.0.3 on 2025-01-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bought_from',
            field=models.CharField(default='IDEAL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='missing_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_missing', models.IntegerField()),
                ('missing_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
