# Generated by Django 5.0.3 on 2025-01-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_bought_from_inventory_on_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='cost',
            new_name='selling_price',
        ),
    ]
