# Generated by Django 5.0.3 on 2025-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_cost_inventory_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sales_record',
            field=models.ManyToManyField(blank=True, related_name='inventory_items', to='inventory.sales'),
        ),
    ]
