# Generated by Django 5.0.3 on 2025-01-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_sales_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='label',
        ),
        migrations.RemoveField(
            model_name='return',
            name='size',
        ),
    ]
