# Generated by Django 5.0.6 on 2024-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cummulative_quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
