# Generated by Django 5.0.6 on 2024-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_cummulative_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cumulative_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
