# Generated by Django 5.0.3 on 2025-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_return_label_remove_return_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
