# Generated by Django 5.0.3 on 2025-01-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sales_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sales'),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
