# Generated by Django 5.0.6 on 2024-08-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_cumulative_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_damaged', models.PositiveIntegerField()),
                ('damage_description', models.TextField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
