# Generated by Django 5.0.6 on 2024-08-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_damaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damaged',
            name='return_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='label',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.PositiveIntegerField(default=0, null=0),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('opening_stock', models.IntegerField()),
                ('closing_stock', models.IntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
