# Generated by Django 5.0.6 on 2024-08-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_damaged_return_date_inventory_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='label',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='return',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
