# Generated by Django 5.0.3 on 2025-01-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory_category'),
        ),
    ]
