# Generated by Django 5.0.6 on 2025-10-22 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(default='NET 30', max_length=100)),
                ('currency_preference', models.CharField(choices=[('USD', 'US Dollar'), ('TRY', 'Turkish Lira'), ('RMB', 'Renminbi'), ('ZAR', 'South African Rand'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('address', models.TextField(blank=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=8),
        ),
        migrations.AddField(
            model_name='inventory_category',
            name='default_markup',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Default markup percentage for this category', max_digits=5),
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text="Supplier's order reference", max_length=100)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_arrival', models.DateField()),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Rate to local currency', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('CUSTOMS', 'Customs Clearance'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('goods_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocation_method', models.CharField(choices=[('VALUE', 'By Value (Recommended)'), ('QUANTITY', 'By Quantity'), ('WEIGHT', 'By Weight'), ('SMART', 'Smart Allocation'), ('CUSTOM', 'Custom')], default='SMART', max_length=20)),
                ('allocation_completed', models.BooleanField(default=False)),
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ImportExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('SHIPPING', 'Shipping/Freight'), ('CUSTOMS_DUTY', 'Customs Duty'), ('VAT', 'VAT/Tax'), ('CLEARING_AGENT', 'Clearing Agent Fee'), ('TRANSPORT', 'Local Transport'), ('INSURANCE', 'Insurance'), ('STORAGE', 'Storage/Warehousing'), ('BANK_CHARGES', 'Bank/Wire Charges'), ('HANDLING', 'Handling Fee'), ('INSPECTION', 'Inspection Fee'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('amount_in_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('date_incurred', models.DateField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.importorder')),
            ],
        ),
        migrations.CreateModel(
            name='ImportOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.importorder')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='inventory.importorder')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('MOBILE_MONEY', 'Mobile Money'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.supplierinvoice')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
