# Generated by Django 5.0.6 on 2025-10-24 12:07

from django.db import migrations, models


def populate_product_codes(apps, schema_editor):
    """Generate product codes for existing inventory items"""
    Inventory = apps.get_model('inventory', 'Inventory')
    Inventory_category = apps.get_model('inventory', 'Inventory_category')
    
    # Track used codes to ensure uniqueness
    used_codes = set()
    
    for item in Inventory.objects.all():
        if not item.product_code:
            # Generate code based on category
            if item.category:
                prefix = item.category.name[:3].upper()
            else:
                prefix = "GEN"  # General category
            
            # Find next available number
            counter = 1
            while True:
                code = f"{prefix}-{counter:04d}"
                if code not in used_codes:
                    item.product_code = code
                    used_codes.add(code)
                    item.save()
                    break
                counter += 1


def reverse_populate_product_codes(apps, schema_editor):
    """Remove product codes (reverse operation)"""
    Inventory = apps.get_model('inventory', 'Inventory')
    Inventory.objects.update(product_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_inventory_weight_and_more'),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name='inventory',
            name='product_code',
            field=models.CharField(blank=True, help_text='Unique product code for quick lookup', max_length=20),
        ),
        # Populate data
        migrations.RunPython(populate_product_codes, reverse_populate_product_codes),
        # Then add the unique constraint
        migrations.AlterField(
            model_name='inventory',
            name='product_code',
            field=models.CharField(blank=True, help_text='Unique product code for quick lookup', max_length=20, unique=True),
        ),
    ]
