# Generated by Django 5.0.6 on 2025-10-24 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventory_product_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('sales', 'Sales Associate'), ('viewer', 'Viewer Only')], default='sales', max_length=20)),
                ('can_make_sales', models.BooleanField(default=True)),
                ('can_process_returns', models.BooleanField(default=True)),
                ('can_apply_discounts', models.BooleanField(default=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum discount % this user can apply', max_digits=5)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_manage_suppliers', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
