# Generated by Django 5.0.6 on 2025-10-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_sales_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorderitem',
            name='is_new_product',
            field=models.BooleanField(default=False, help_text='Check if this is a new product to be created'),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='inventory.inventory_category'),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='quantity_received',
            field=models.IntegerField(default=0, help_text='Quantity actually received'),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_import_order',
            field=models.ForeignKey(blank=True, help_text='Import order this product was first added from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='inventory.importorder'),
        ),
        migrations.AlterField(
            model_name='importorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to='inventory.inventory'),
        ),
    ]
