# Generated by Django 5.0.6 on 2025-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_customer_glaccount_arinvoice_arpayment_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('LAYBY', 'Layby')], default='CASH', max_length=10),
        ),
    ]
