# Generated by Django 5.0.6 on 2025-10-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_customer_opt_in_for_emails_customer_purchase_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arpayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='arpayment',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='laybyitem',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='laybyitem',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='laybypayment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='laybypayment',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='laybyplan',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ARInvoice',
        ),
        migrations.DeleteModel(
            name='ARPayment',
        ),
        migrations.DeleteModel(
            name='GLAccount',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalLine',
        ),
        migrations.DeleteModel(
            name='LaybyItem',
        ),
        migrations.DeleteModel(
            name='LaybyPayment',
        ),
        migrations.DeleteModel(
            name='LaybyPlan',
        ),
    ]
