# Generated by Django 5.0.6 on 2025-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_arpayment_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='posted_to_cashbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='posted_to_gl',
            field=models.BooleanField(default=False),
        ),
    ]
