# Generated by Django 5.0.6 on 2025-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_sales_posted_to_cashbook_sales_posted_to_gl'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lead_time_days',
            field=models.IntegerField(default=0, help_text='Supplier lead time in days'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_point',
            field=models.IntegerField(default=0, help_text='Minimum stock level before reordering'),
        ),
    ]
