# Generated by Django 5.0.3 on 2025-11-14 12:41

import django_resized.forms
import inventory.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventory_lead_time_days_inventory_reorder_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Main product image (auto-resized to 800x600, max 5MB)', keep_meta=True, null=True, quality=85, scale=None, size=[800, 600], upload_to='products/images/', validators=[inventory.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Thumbnail (auto-generated 200x200)', keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='products/thumbnails/'),
        ),
    ]
