# Generated by Django 5.0.6 on 2025-11-14 13:08

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_inventory_image_inventory_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['smart', 'smart'], force_format='JPEG', help_text='Thumbnail (auto-generated 200x200 with smart crop)', keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to='products/thumbnails/'),
        ),
    ]
