# Generated by Django 5.0.6 on 2025-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventory_bought_from_alter_inventory_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorderitem',
            name='old_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original selling price before allocation', max_digits=10, null=True),
        ),
    ]
