# Generated by Django 5.0.6 on 2025-11-21 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_old_selling_price_to_import_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', help_text='Your business name', max_length=200)),
                ('company_address', models.TextField(blank=True, help_text='Full business address')),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('tax_registration_number', models.CharField(blank=True, help_text='VAT/TIN number', max_length=50)),
                ('company_logo', models.ImageField(blank=True, help_text='Logo for receipts and invoices', null=True, upload_to='company/')),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('ZAR', 'South African Rand (R)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('ZWL', 'Zimbabwe Dollar (Z$)'), ('BWP', 'Botswana Pula (P)'), ('KES', 'Kenyan Shilling (KSh)'), ('NGN', 'Nigerian Naira (₦)')], default='USD', help_text='Base currency for all transactions', max_length=3)),
                ('currency_symbol_position', models.CharField(choices=[('before', 'Before ($100)'), ('after', 'After (100$)')], default='before', max_length=10)),
                ('decimal_places', models.IntegerField(choices=[(0, '0'), (2, '2')], default=2, help_text='Decimal places for prices')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax/VAT rate (%)', max_digits=5)),
                ('financial_year_start', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Month financial year begins')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Default credit limit for new customers', max_digits=12)),
                ('default_payment_terms_days', models.IntegerField(default=30, help_text='Default payment terms (Net X days)')),
                ('credit_grace_period_days', models.IntegerField(default=0, help_text='Days after due date before considered overdue')),
                ('enable_interest_charges', models.BooleanField(default=False, help_text='Enable interest on overdue accounts')),
                ('interest_rate_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Monthly interest rate (%) - for future use', max_digits=5)),
                ('layby_minimum_deposit_percent', models.DecimalField(decimal_places=2, default=20, help_text='Minimum deposit required (%)', max_digits=5)),
                ('layby_max_duration_days', models.IntegerField(default=90, help_text='Maximum days to complete layby')),
                ('layby_cancellation_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fee charged on layby cancellation (%)', max_digits=5)),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Default low stock warning level')),
                ('default_markup_percent', models.DecimalField(decimal_places=2, default=40, help_text='Default markup percentage for new products', max_digits=5)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow sales when stock is zero')),
                ('track_stock_movements', models.BooleanField(default=True, help_text='Log all stock changes')),
                ('receipt_prefix', models.CharField(default='RCP', help_text='Prefix for receipt numbers', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('import_order_prefix', models.CharField(default='IO', help_text='Prefix for import order numbers', max_length=10)),
                ('layby_prefix', models.CharField(default='LB', help_text='Prefix for layby plan numbers', max_length=10)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=50, help_text='Maximum discount allowed (%)', max_digits=5)),
                ('require_customer_for_sales', models.BooleanField(default=False, help_text='Require customer for all sales')),
                ('print_receipt_automatically', models.BooleanField(default=False, help_text='Auto-print receipt after sale')),
                ('date_format', models.CharField(choices=[('Y-m-d', 'YYYY-MM-DD (2025-01-15)'), ('d/m/Y', 'DD/MM/YYYY (15/01/2025)'), ('m/d/Y', 'MM/DD/YYYY (01/15/2025)'), ('d-m-Y', 'DD-MM-YYYY (15-01-2025)'), ('d M Y', 'DD Mon YYYY (15 Jan 2025)')], default='Y-m-d', max_length=20)),
                ('time_format', models.CharField(choices=[('H:i', '24-hour (14:30)'), ('h:i A', '12-hour (2:30 PM)')], default='H:i', max_length=10)),
                ('items_per_page', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
