# Generated by Django 5.0.6 on 2025-11-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_add_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which attributes appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attribute Type',
                'verbose_name_plural': 'Attribute Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Enable if this product has size/color variants'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant_attributes',
            field=models.ManyToManyField(blank=True, help_text='Attribute types used for variants (e.g., Size, Color)', to='inventory.attributetype'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('display_value', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code for color swatches (e.g., #000000)', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.attributetype')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'ordering': ['attribute_type', 'display_order', 'value'],
                'unique_together': {('attribute_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique SKU for this variant', max_length=50, unique=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product default', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product default', max_digits=10, null=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0, help_text='Minimum stock level before reordering')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('attribute_values', models.ManyToManyField(related_name='variants', to='inventory.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant sold (if product has variants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='inventory.productvariant'),
        ),
    ]
