# Generated by Django 5.0.6 on 2026-04-22 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_damaged_inventory_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code for receipts, SKUs, barcodes (e.g. 'BBY', 'CLO')", max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('vat_number_override', models.CharField(blank=True, help_text='Per-shop VAT number if different from SiteSettings (future ZIMRA per-shop registration)', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_shop',
            field=models.ForeignKey(blank=True, help_text="The shop this user operates at by default (cashiers pinned to their till's shop)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='inventory.shop'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.shop')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.shop')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0, help_text='Per-shop reorder point; 0 means fall back to product/variant level')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stock', to='inventory.inventory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_rows', to='inventory.shop')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_stock', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Shop Stock',
                'verbose_name_plural': 'Shop Stock',
                'ordering': ['shop', 'inventory_item'],
                'unique_together': {('shop', 'inventory_item', 'variant')},
            },
        ),
    ]
