# Generated by Django 5.0.6 on 2026-04-22 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_sales_receipt_number_shop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('terms', models.CharField(choices=[('IMMEDIATE', 'Paid Immediately'), ('CREDIT', 'On Account (AR)'), ('LAYBY', 'Layby')], default='IMMEDIATE', max_length=12)),
                ('tender_type', models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], default='CASH', max_length=16)),
                ('tender_reference', models.CharField(blank=True, help_text='EcoCash agent code, bank transfer ref, or card auth number', max_length=100)),
                ('subtotal_excl_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_incl_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('posted_to_gl', models.BooleanField(default=False)),
                ('posted_to_cashbook', models.BooleanField(default=False)),
                ('stock_posted', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_rung', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tickets', to='inventory.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_tickets', to='inventory.shop')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Ticket',
                'verbose_name_plural': 'Sales Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_incl_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Currency discount on this line (not percent).', max_digits=10)),
                ('is_vat_exempt', models.BooleanField(default=False)),
                ('vat_rate_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('line_subtotal_excl_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total_incl_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_lines', to='inventory.inventory')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_lines', to='inventory.productvariant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.salesticket')),
            ],
            options={
                'verbose_name': 'Sales Line',
                'verbose_name_plural': 'Sales Lines',
                'ordering': ['id'],
            },
        ),
    ]
