# Generated by Django 5.0.6 on 2026-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_salesticket_salesline'),
    ]

    operations = [
        migrations.AddField(
            model_name='damaged',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damaged_items', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='destination_shop',
            field=models.ForeignKey(blank=True, help_text="Which shop this line's stock is destined for when goods are received.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_items', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='missing_inventory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missing_inventory_records', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='return',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.shop'),
        ),
    ]
