# Generated by Django 5.0.6 on 2026-04-22 14:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_damaged_shop_importorderitem_destination_shop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('z_number', models.PositiveIntegerField()),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ecocash_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bank_transfer_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('card_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Physical cash counted in the drawer at close', max_digits=14, null=True)),
                ('cash_variance', models.DecimalField(blank=True, decimal_places=2, help_text='counted_cash − cash_total; negative = shortage', max_digits=14, null=True)),
                ('cashier_summary', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_cashups_closed', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_cashups', to='inventory.shop')),
            ],
            options={
                'verbose_name': 'Daily Cash-Up',
                'verbose_name_plural': 'Daily Cash-Ups',
                'ordering': ['-date', 'shop'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
