# Generated by Django 5.0.6 on 2026-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_z_report_daily_cashup'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, help_text='Zero-rated for VAT (e.g. basic foodstuffs)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_vat_exempt',
            field=models.BooleanField(blank=True, help_text='Override product VAT status. Leave blank to inherit.', null=True),
        ),
    ]
