# Generated by Django 5.0.6 on 2026-04-22 15:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_vat_exempt_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damaged',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damaged',
            name='posted_to_gl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damaged',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damaged',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damaged_records', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='is_restockable',
            field=models.BooleanField(default=True, help_text='If False, goods are written off to Inventory Loss instead of restocked.'),
        ),
        migrations.AddField(
            model_name='return',
            name='posted_to_gl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_tender',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ECOCASH', 'EcoCash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('STORE_CREDIT', 'Store Credit'), ('AR_CREDIT', 'Credit Note on AR')], default='CASH', max_length=16),
        ),
        migrations.AddField(
            model_name='return',
            name='restock_to_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_restocked', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='return',
            name='ticket_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='inventory.salesline'),
        ),
    ]
