# Generated by Django 5.0.6 on 2026-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_returns_damaged_ticket_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Code-128 barcode. Auto-generated from product_code on first save.', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Code-128 barcode. Auto-generated from SKU on first save.', max_length=32, null=True, unique=True),
        ),
    ]
