# Generated by Django 5.0.6 on 2026-04-23 06:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_product_barcodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('destination', models.CharField(help_text='Country or region, e.g. "China — Guangzhou"', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('total_travel_expenses_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Flights, accommodation, meals, agent fees. Allocated across orders by value.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocking_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stocking Trip',
                'verbose_name_plural': 'Stocking Trips',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='importorder',
            name='stocking_trip',
            field=models.ForeignKey(blank=True, help_text='Optional — groups orders made on a single buying trip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_orders', to='inventory.stockingtrip'),
        ),
    ]
