# Generated by Django 5.0.6 on 2026-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_stocking_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('sales', 'Sales Associate'), ('accountant', 'Accountant (Read-only)'), ('viewer', 'Viewer Only')], default='sales', max_length=20),
        ),
    ]
