# Generated by Django 5.0.6 on 2026-05-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='vat_enabled',
            field=models.BooleanField(default=False, help_text='Master VAT switch. When OFF: tickets post Cr Revenue full incl-amount, VAT lines and Output VAT Payable (2400) are bypassed. Flip ON only after ZIMRA fiscalisation is in place.'),
        ),
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, help_text="Source Excel sheet name (e.g. 'daily sales', 'credit clients').", max_length=100)),
                ('row_index', models.IntegerField(help_text="1-based row number in the source sheet (matches Excel's row number).")),
                ('row_data', models.JSONField(default=dict, help_text='Raw parsed row as a dict of {column_name: cell_value}.')),
                ('record_date', models.DateField(blank=True, db_index=True, help_text='Best-effort date extracted from the row, for sorting/filtering.', null=True)),
                ('source_workbook', models.CharField(blank=True, help_text='Source workbook filename for traceability.', max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shop', models.ForeignKey(blank=True, help_text='Shop the row belongs to. NULL for corporate/multi-shop rows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_records', to='inventory.shop')),
            ],
            options={
                'ordering': ['-record_date', 'sheet_name', 'row_index'],
                'indexes': [models.Index(fields=['sheet_name', 'record_date'], name='inventory_h_sheet_n_2e2396_idx')],
            },
        ),
    ]
