"""
Django settings for inventorySystem project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*&gmmgruw$ra6j)8(=*m97@fs&t*n!a82461-p&z3mj&1&7(#0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


CSRF_TRUSTED_ORIGINS = [
    'https://ims-production-45b3.up.railway.app',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# If you also need to update ALLOWED_HOSTS
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'ims-production-45b3.up.railway.app',
    '.railway.app'  # Allows all railway.app subdomains

]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory.apps.InventoryConfig',
    'accounting',
    'crispy_forms',
    'bootstrap4',
    'crispy_bootstrap4',
    'inventory.templatetags.custom_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'inventorySystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventorySystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Database Configuration
# Railway (production): Uses DATABASE_URL environment variable pointing to PostgreSQL
# Local (development): Falls back to SQLite if DATABASE_URL is not set
# DATABASES = {
#     'default': dj_database_url.config(
#         default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ims_database',
#         'USER': 'Walter',
#         'PASSWORD': 'Walter6711',
#         'HOST': 'localhost',  
#         'PORT': '3306',       
#     }
# }

# Database configuration
# Priority order:
# 1. DATABASE_PUBLIC_URL - for local Railway CLI commands (uses TCP proxy, works from outside Railway)
# 2. DATABASE_URL - for production inside Railway (uses private domain)
# 3. Railway env vars - fallback using individual PostgreSQL environment variables
# 4. SQLite - for local development without Railway

# Check for DATABASE_PUBLIC_URL first (for local Railway CLI usage)
DATABASE_PUBLIC_URL = os.environ.get('DATABASE_PUBLIC_URL')
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_PUBLIC_URL:
    # Use public URL for local Railway CLI commands (works from outside Railway network)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_PUBLIC_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif DATABASE_URL:
    # Use private URL for production inside Railway (only works inside Railway network)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('RAILWAY_ENVIRONMENT') or os.environ.get('RAILWAY'):
    # Railway environment detected - use Railway PostgreSQL credentials from env vars
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PGDATABASE', os.environ.get('POSTGRES_DB', 'railway')),
            'USER': os.environ.get('PGUSER', os.environ.get('POSTGRES_USER', 'postgres')),
            'PASSWORD': os.environ.get('PGPASSWORD', os.environ.get('POSTGRES_PASSWORD', '')),
            'HOST': os.environ.get('PGHOST', os.environ.get('RAILWAY_TCP_PROXY_DOMAIN', 'maglev.proxy.rlwy.net')),
            'PORT': os.environ.get('PGPORT', os.environ.get('RAILWAY_TCP_PROXY_PORT', '57897')),
        }
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Media files (User uploads - product images, invoices, receipts, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

LOGIN_REDIRECT_URL = 'inventory'
LOGIN_URL = 'login'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
