# Generated by Django 5.0.6 on 2025-11-03 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('WAGES', 'Wages'), ('FREIGHT', 'Freight'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('gl_account', models.ForeignKey(limit_choices_to={'type': 'EXP'}, on_delete=django.db.models.deletion.PROTECT, to='accounting.glaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
