# Generated by Django 5.0.6 on 2025-11-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='laybyplan',
            name='ar_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layby_plan', to='accounting.arinvoice'),
        ),
    ]
