# Generated by Django 5.0.6 on 2025-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_laybyplan_ar_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIAB', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXP', 'Expense'), ('CONTRA_REV', 'Contra-Revenue')], max_length=15),
        ),
    ]
