# Generated by Django 5.0.6 on 2026-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_arinvoice_due_date_and_more'),
        ('inventory', '0031_damaged_shop_importorderitem_destination_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoice', to='inventory.salesticket'),
        ),
        migrations.AddField(
            model_name='arpayment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbook_entries', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='laybypayment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layby_payments', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='laybyplan',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layby_plans', to='inventory.shop'),
        ),
        migrations.AddField(
            model_name='laybyplan',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layby_plan', to='inventory.salesticket'),
        ),
    ]
