# Generated by Django 5.0.6 on 2026-04-22 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_arinvoice_shop_arinvoice_ticket_arpayment_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Input VAT recoverable (portion of amount). 0 for exempt/non-VATable expenses.', max_digits=12),
        ),
    ]
